sudo: false
language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo clean && hexo g -d
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public